<?php

/**
 * Implements hook_menu().
 */
function cwrc_eap_menu() {
  $items['islandora/object/%islandora_object/edit-entity'] = array(
    'title' => 'Edit',
    'page callback' => 'cwrc_eap_edit_entity',
    'access callback' => 'cwrc_eap_edit_entity_access',
    'access arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Page callback, just dumps an error message, as editing is all javascript
 * based for this.
 */
function cwrc_eap_edit_entity() {
  return t('You must have javascript enabled to edit CWRC entities.');
}

/**
 * Ensures this object is a valid entity and then ensures user has edit access.
 */
function cwrc_eap_edit_entity_access($object) {
  module_load_include('inc', 'islandora_cwrc_writer', 'includes/utilities');
  $valid_types = islandora_cwrc_writer_valid_entity_types();
  if (empty(array_intersect($valid_types, $object->models))) {
    return false;
  } else {
    return islandora_object_manage_access_callback(
      array(
        ISLANDORA_MANAGE_PROPERTIES,
        ISLANDORA_METADATA_EDIT,
        ISLANDORA_ADD_DS,
        ISLANDORA_PURGE,
        ISLANDORA_INGEST,
      ), $object);
  }
}

/**
 * Implementation of hook_libraries_info().
 *
 * Defines the CWRC Dialogs library.
 */
function cwrc_eap_libraries_info() {
  return array(
    'CWRC-Dialogs' => array(
      'name' => 'CWRC Dialogs',
      'version' => 'dev-master',
      'vendor url' => 'http://www.cwrc.ca/projects/infrastructure-projects/technical-projects/cwrc-writer/',
      'download url' => 'http://github.com/cwrc/CWRC-Dialogs',
      'files' => array(
        'js' => array(
          'js/lib/jquery-1.11.0.js',
          'js/lib/jquery-ui-1.10.4.custom.js',
          'js/lib/knockout-2.3.0.js',
          'js/lib/bootstrap.js',
          'js/lib/bootstrap-datepicker.js',
          'js/cwrc-api.js',
          'js/cD.js',
        ),
        'css' => array(
          'css/bootstrap.css',
          'css/datepicker.css',
          'font-awesome/css/font-awesome.min.css',
          'css/cD.css',
        ),
      ),
    ),
  );
}

/**
 * Implementation of hook_preprocess_menu_local_task().
 *
 * When our link is rendered as a local task we load the library and attach
 * relevant javascript and settings so that we can do our job here.
 */
function cwrc_eap_preprocess_menu_local_task(&$variables) {
  if ($variables['element']['#link']['path'] == 'islandora/object/%/edit-entity') {
    global $base_url;

    // Add our css and javascripts.
    libraries_load('CWRC-Dialogs');
    drupal_add_js(drupal_get_path('module', 'cwrc_eap') . '/js/edit-eap.js');

    // Create settings for edit dialog.
    $object = menu_get_object('islandora_object', 2);
    $settings = array(
      'base_url' => $base_url,
      'entity_type' => islandora_cwrc_writer_get_entity_type($object),
      'opts' => array(
        'id' => $object->id,
        'name' => $object->label,
        'data' => $object[islandora_cwrc_writer_entity_content_datastream_id($object)]->content,
        'repository' => 'cwrc',
      ),
    );
    drupal_add_js(array('cwrc_eap' => $settings), 'setting');

    // Inject ID attribute into the render element.
    $variables['element']['#link']['options']['attributes']['id'] = 'cwrc-eap-edit-link';
    $variables['element']['#link']['localized_options']['attributes']['id'] = 'cwrc-eap-edit-link';
  }
}
